train_params:
  experiment_name: multi_scratch_vessmap_resnet18_unet_TESTE
  run_name: ''
  validate_every: 5
  dataset_path: /media/wesleygalvao/1_TB_LINUX/Datasets/blood_vessels/VessMAP
  dataset_class: vessmap_few
  split_strategy: ''
  channels: all
  resize_size: 256 256
  model_class: resnet18_unet
  num_epochs: 500
  validation_metric: Dice
  bs_train: 8
  bs_valid: 20
  weight_decay: 0.0
  lr: 0.01
  lr_decay: 1.0
  optimizer: adam
  num_workers: 12
  suppress_best_checkpoint: ''
  checkpoint_every: -1
experiment_params:
  min_samples: 1
  max_samples: 20
  runs: 5
  reps: 3
  with_replacement: false
  output_dir: experiments
  csv_path: /media/wesleygalvao/1_TB_LINUX/Datasets/blood_vessels/VessMAP/train.csv
  step: 2
  weights_id: FromScratch
test_params:
  run_path: ''
  dataset_path: /media/wesleygalvao/1_TB_LINUX/Datasets/blood_vessels/VessMAP
  dataset_class: vessmap
  model_class: resnet18_unet
  resize_size: 256 256
  checkpoint_type: last
  inference_dir_name: inference_results
  delete_checkpoint: true
  batch_inference: true
  enable_inference: true
  force_headless: true
  skip_boxplot: true
  max_inference_retries: 1
  delete_only_on_success: true
  aggregate_inference_means: true
