augmentation_strategy: null
benchmark: false
bs_train: 200
bs_valid: 64
copy_model_every: 0
dataset_class: multiple
dataset_params: {}
dataset_path: /media/wesleygalvao/1_TB_LINUX/Datasets/blood_vessels/
deterministic: false
device: cuda:0
disable_tqdm: false
experiment_name: resnet18_unet_vess_shape
experiments_path: experiments
ignore_class_weights: false
log_wandb: true
loss_function: cross_entropy
lr: 0.01
lr_decay: 1.0
maximize_validation_metric: false
meta: ''
model_class: resnet18_unet
model_params: {}
momentum: 0.9
num_epochs: 200
num_workers: 8
optimizer: adam
patience: null
profile: false
profile_batches: 3
profile_verbosity: 0
resize_size:
- 384
- 384
run_name: train_size_50k_200_epochs
save_val_imgs: true
seed: 0
split_strategy: '0.2'
timestamp_start: 2025-04-08-23:36:44
use_amp: false
val_img_indices:
- 0
- 1
- 2
- 3
validate_every: 5
validation_metric: Val loss VessMAP
wandb_project: resnet18_unet_vess_shape
weight_decay: 0.0
weights_strategy: null
