# Section of training parameters
train_params:
  # experiment_name: multi_finetune_on_drive_resnet18_A
  experiment_name: multi_finetune_on_drive_resnet50_A
  run_name: ''
  weights_strategy: /media/wesleygalvao/1_TB_LINUX/models_results/01_pre-trained_on_vess_shape/resnet50_ts:50k_bs-train:96_ep:3000_lr:0.001_lr-decay:0.0_wd:0.0001_opt:adam_class1:0.10_FP16/checkpoint.pt
  validate_every: 5
  save_val_imgs: ''
  val_img_indices: '0 1 2'
  dataset_path: /media/wesleygalvao/1_TB_LINUX/Datasets/blood_vessels/DRIVE
  dataset_class: drive_few
  split_strategy: ''
  resize_size: '512 512'
  # model_class: resnet18_unet
  model_class: resnet50_unet
  num_epochs: 300
  validation_metric: Dice
  maximize_validation_metric: ''
  bs_train: 8
  bs_valid: 20
  weight_decay: 0.0
  lr: 0.01
  lr_decay: 1.0
  ignore_class_weights: '' # Ignore class weights during training
  optimizer: adam
  num_workers: 12
  log_wandb: ''
  # wandb_project: multi_finetune_on_drive_resnet18_A
  wandb_project: multi_finetune_on_drive_resnet50_A
  wandb_group: ''
  #suppress_checkpoint: '' # Suppress checkpoint saving, if enabled
  suppress_best_checkpoint: '' # Suppress best checkpoint saving, if enabled
  checkpoint_every: -1 # Save checkpoints every last epoch

# Section of parameters for experiments in series
experiment_params:
  min_samples: 1
  max_samples: 16
  runs: 5
  reps: 3
  with_replacement: False
  output_dir: experiments
  step: 2
  csv_path: /media/wesleygalvao/1_TB_LINUX/Datasets/blood_vessels/DRIVE/train.csv
  weights_id: A
  delete_checkpoint: True
  # Run inference only after finishing all runs*reps of each num_samples value
  batch_inference: True
  # Master switch to enable/disable any inference without removing test_params
  enable_inference: True

# Section of parameters for test/inference
test_params:
  run_path: ""
  dataset_path: "/media/wesleygalvao/1_TB_LINUX/Datasets/blood_vessels/DRIVE"
  dataset_class: drive
  #model_class: resnet18_unet
  model_class: resnet50_unet
  use_amp: ""
  save_inference_images: ""
  checkpoint_type: "last"
  inference_dir_name: "inference_results"
  
