benchmark: false
channels: null
checkpoint_type: best
dataset_class: dca1
dataset_params: {}
dataset_path: /media/wesleygalvao/1_TB_LINUX/Datasets/blood_vessels/DCA1
deterministic: false
device: cuda:0
encoder_weights: imagenet
force_headless: true
imagenet_normalize: false
inference_dir_name: /tmp/vss_zero_shot_raw/resnet50_imagenet/inference_results_dca1
model_class: resnet50_unet
model_params: {}
resize_size:
- 288
- 288
run_path: .
save_inference_images: false
seed: 0
skip_boxplot: true
skip_checkpoint_loading: true
threshold: 0.5
tta_type: none
use_amp: true
